// Rewrites the script section of docs/PRESENTATION.md from notes.js.
const fs = require("fs");
const path = require("path");
const NOTES = require("./notes.js");

const target = path.join(__dirname, "..", "docs", "PRESENTATION.md");
const BEGIN = "<!-- script:begin (generated by deck/presentation-md.js) -->";
const END = "<!-- script:end -->";

const words = (text) => text.split(/\s+/).filter(Boolean).length;
const clock = (minutes) => {
  const seconds = Math.round(minutes * 60);
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
};

let elapsed = 0;
const rows = [];
const sections = [];
NOTES.forEach((slide, index) => {
  const start = elapsed;
  elapsed += slide.minutes;
  rows.push(`| ${index + 1} | ${slide.title} | ${clock(start)} | ${words(slide.notes)} |`);
  sections.push(`### ${index + 1}. ${slide.title}\n\n${slide.notes}\n`);
});

const total = NOTES.reduce((sum, slide) => sum + words(slide.notes), 0);
const generated = [
  BEGIN,
  "",
  `| Slide | Title | Starts at | Words |`,
  `|---|---|---|---|`,
  ...rows,
  "",
  `${total} words in all; the plan ends at ${clock(elapsed)}, which leaves room inside a fifteen-minute slot.`,
  "",
  ...sections,
  END,
].join("\n");

const current = fs.readFileSync(target, "utf8");
const from = current.indexOf(BEGIN);
const to = current.indexOf(END);
if (from < 0 || to < 0) throw new Error("markers not found in docs/PRESENTATION.md");
fs.writeFileSync(target, current.slice(0, from) + generated + current.slice(to + END.length));
console.log("wrote", target);
